name: gha-migration/rush_1
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    timeout-minutes: 60
    env:
      APP_NAME: demo-app
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/download-artifact@v4.1.0
      with:
        name: test
        path: .
    - run: echo "Deploying Application..."
    - run: cat test.txt
    - run: echo "Deployment Successful!"
