name: gha-migration/rush_1
on:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    timeout-minutes: 60
    env:
      APP_NAME: demo-app
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: echo "Building $APP_NAME..."
    - run: echo "Docker Image Build Successful" > build.txt
    - run: cat build.txt
    - uses: actions/upload-artifact@v4.1.0
      if: success()
      with:
        name: "${{ github.job }}"
        retention-days: 1
        path: build.txt
