name: gha-migration/rush_1
on:
  push:
  workflow_call: 
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    timeout-minutes: 60
    env:
      APP_NAME: demo-app
    steps:
   # - name: Install Git and Git LFS
      #run: |
         # apt-get update
         # apt-get install -y git git-lfs
          #git lfs install
    - uses: actions/checkout@v4.1.0
    #- name: Download Build Artifact
      #uses: actions/download-artifact@v4.1.0
     # with:
       # name: build
       # path: .     
    - uses: actions/download-artifact@v4.1.0
      with:
        name: test
        path: .
    - run: echo "Deploying Application..."
    - run: cat test.txt
    - run: echo "Deployment Successful!"
