name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build.txt

      - run: cat build.txt

      - run: echo "Running Tests..."

      - run: echo "Tests Passed" > test.txt

      - uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.txt
